### ISSUE TITLE
Does not work when running in Tomcat 7

### ISSUE THREAD

**Issue by adamretter** [eXist-db/monex#9]
When you try and access Monex from the dashboard of eXist 2.2 HEAD deployed as a WAR file in Tomcat 7, you get the following error when it hits `http://localhost:8080/exist/apps/monex/index.html`:

``` xml
<exception>
  <path>/db/apps/monex/modules/view.xql</path>
  <message>
exerr:ERROR error found while loading module app: Error while loading module app.xql: error found while loading module console: Cannot find module class from EXPath repository: org.exist.console.xquery.ConsoleModule
  </message>
</exception>
```

**Comment by duncdrum** [comment]
Still happening on 3.x, with monex 0.9.8, and  tomcat 7.0.56. Any reason why the PR from 2014 is still open?

**Comment by rvdb** [comment]
I see this issue has been closed, but I'm still seeing the exact same error when deploying eXist-4.0.0 in Tomcat-7.0.50. Is there a solution meanwhile that I've missed?

**Comment by duncdrum** [comment]
@rvdb a related issue reported to my cbdb-data repo was closed, this issue about running monex on tomcat is still open, and not solved as far as I know

**Comment by rvdb** [comment]
@duncdrum Ok, sorry, I was confused by the `Closed` label for your referring issue. Still hoping for a fix, then... (would be really nice to finally have Monex inside Tomcat!)

**Comment by joewiz** [comment]
Fixed by #11.

**Comment by rvdb** [comment]
Unfortunately, it's still not working here... I've rebuilt monex at https://github.com/eXist-db/monex/commit/697318688871c7dd7ded36877a885b2dd68b910e, in following environment:

- eXist-4.0.0
- tomcat-7.0.85
- jdk1.8.0_161
- Windows 7 Professional, 64 bit

When accessing the Monex app, I still get the same error:

    <exception>
      <path>/db/apps/monex/modules/view.xql</path>
      <message>exerr:ERROR error found while loading module indexes: Error while loading module indexes.xqm: error found while loading module console: Cannot find module class from EXPath repository: org.exist.console.xquery.ConsoleModule</message>
    </exception>

**Comment by joewiz** [comment]
@dizzzz @duncdrum Apparently #11 did not fix the issue. 

Does anyone have a suggestion about what is tripping up monex here? It seems to be unable to resolve the path to the console module (which should be registered when monex is installed) when monex is installed within tomcat.

**Comment by dizzzz** [comment]
strange.....

**Comment by duncdrum** [comment]
@joewiz I applied the fix from the PR on a colleagues tomcat when debugging his system, and it worked (around exist 3.3-5). Outside of that I have zero experience with Tomcat, so I don't even know where to begin.

**Comment by joewiz** [comment]
Thanks, all for reporting and testing the fixes to the various issues reported here. I think we can close this one now. If there are any remaining Tomcat issues, please open a new issue.
